language: node_js
services: mongodb
node_js:
  - "0.10"
  - "4.4.3"
sudo: required
before_install:
  - sudo apt-get update
  - sudo apt-get install --assume-yes apache2-utils
  - npm install -g npm@2.13.5
  - npm install -g grunt-cli
  - npm config set strict-ssl false
install: npm install

matrix:
  # The acceptance tests only work with node 4 or higher.
  exclude:
  # Remove the original job for node 4.4.3, without the acceptance tests.
  - node_js: "4.4.3"
  include:
  # Include an updated job, with the acceptance tests. This way we're not
  # running the 4.4.3 build twice with one build including acceptance tests.
  - node_js: "4.4.3"
    script:
      - npm link
      - git clone https://github.com/feedhenry/sync-acceptance-testing.git
      - cd sync-acceptance-testing
      - npm install
      - npm link fh-mbaas-api
      - npm test
